import { InMemoryDbService } from 'angular-in-memory-web-api';


export class Database implements InMemoryDbService {
  
  createDb() {

    const items = 
   [
    {
      id: 1,
      name: "Night table",
      price: 9500,
      special: "New",
      src: "../../assets/images/bedroom-night-table.jpg",
      alt: "night-table",
      image: "../../assets/images/nighttable.jpg",
      description: "Beautiful night table to match every style and budget",
      category: "Bedroom",
      quantity: 1,
    }, 
    {
      id: 2,
      name: "Bedroom",
      price: 350000,
      special: "",
      src: "../../assets/images/bedRoom.jpg",
      alt: "bedroom",
      image: "../../assets/images/bedroom-bedroom.jpg",
      description: "Beautiful bedroom to match every style and budget",
      category: "Bedroom",
      quantity: 1,
    },
  {
    id: 3,
    name: "Table",
    price: 40000,
    special: "",
    src: "../../assets/images/living-room-table.jpg",
    alt: "table",
    image: "../../assets/images/radniSto.jpg",
    description: "Beautiful table/desk to match every style and budget",
    category: "Living Room",
    quantity: 1,
  }, 
  {
    id: 4,
    name: "Sofa",
    price: 40000,
    special: "Sale",
    src: "../../assets/images/living-room-sofa.jpg",
    alt: "sofa",
    image: "../../assets/images/sofa.jpg",
    description: "Beautiful sofa to match every style and budget",
    category: "Living Room",
    quantity: 1,
  }, 
  {
    id: 5,
    name: "Chair",
    price: 5000,
    special: "",
    src: "../../assets/images/living-room-chair.jpg",
    alt: "chair",
    image: "../../assets/images/stolica_sto.jpg",
    description: "Beautiful chair to match every style and budget",
    category: "Living Room",
    quantity: 1,
  }, 
  {
    id: 6,
    name: "Armchair",
    price: 9000,
    special: "",
    src: "../../assets/images/living-room-armchair.jpg",
    alt: "armchair",
    image: "../../assets/images/living-room-armchair.jpg",
    description: "Beautiful armchair to match every style and budget",
    category: "Living Room",
    quantity: 1,
  }, 
  {
    id: 7,
    name: "Cosy couch",
    price: 350000,
    special: "",
    src: "../../assets/images/living-room-cosy-couch.jpg",
    alt: "cosy couch",
    image: "../../assets/images/krevet.jpg",
    description: "Beautiful cosy couch to match every style and budget",
    category: "Living Room",
    quantity: 1,
  }, 
  {
    id: 8,
    name: "Pillow",
    price: 1125,
    special: "",
    src: "../../assets/images/living-room-pillow.jpg",
    alt: "pillow",
    image: "../../assets/images/living-room-pillow.jpg",
    description: "Beautiful pillow to match every style and budget",
    category: "Living Room",
    quantity: 1,
  },
  {
    id: 9,
    name: "Kitchen",
    price: 89000,
    special: "Bestseller",
    src: "../../assets/images/kitchen-kitchen.jpg",
    alt: "bedroom",
    image: "../../assets/images/kitchen-kitchen.jpg",
    description: "Beautiful kitchen to match every style and budget",
    category: "Kitchen",
    quantity: 1,
  },
  {
    id: 10,
    name: "Bar stool",
    price: 3000,
    special: "",
    src: "../../assets/images/kitchen-bar-stool.jpg",
    alt: "bedroom",
    image: "../../assets/images/kitchen-bar-stool.jpg",
    description: "Beautiful bar stool to match every style and budget",
    category: "Kitchen",
    quantity: 1,
  },
  {
    id: 11,
    name: "Dining table",
    price: 50000,
    special: "",
    src: "../../assets/images/kitchen-dining-table.jpg",
    alt: "dining table",
    image: "../../assets/images/kitchen-dining-table.jpg",
    description: "Beautiful dining table to match every style and budget",
    category: "Kitchen",
    quantity: 1,
  },

];
return {items};

}
}